Repository AgoraSpaceDAO/agora-frontend, pull requests merged in 2021-07, with the labels that each got.

#37 SSR compatible solution for color palette aware modals
  src/components/community/Context.tsx
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Platforms/components/JoinModal/JoinModal.tsx
  src/components/community/Platforms/components/LeaveModal/LeaveModal.tsx
  src/components/community/hooks/useContainerRef.ts
Labels: invalid

#39 Level access indicator (I34)
  src/components/community/Levels/Levels.tsx
  src/components/community/Levels/components/AccessIndicator.tsx
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/Level/index.ts
Labels: enhancement

#29 stake and token allowance machine refactor
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Levels/components/StakingModal/hooks/useStakingMachine.ts
  src/components/community/Levels/components/StakingModal/hooks/useStakingModalMachine.ts
  src/components/community/hooks/useTokenAllowance.ts
  src/components/community/hooks/useTokenAllowanceMachine.ts
Labels: agora-frontend, refactor

#45 Updated contract
  src/constants/agoraSpaceABI.json
  src/temporaryData/communities.ts
Labels: agora-frontend, invalid

#46 Display "Wallet not connected" for open levels
  src/components/community/Levels/components/Level/hooks/useLevelAccess.ts
Labels: agora-frontend, invalid

#48 general error processing function for MetaMask errors
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Platforms/components/JoinModal/JoinModal.tsx
  src/components/community/Platforms/components/JoinModal/hooks/useJoinModalMachine.ts
  src/components/community/Platforms/components/JoinModal/hooks/usePersonalSign.ts
  src/components/community/Platforms/components/JoinModal/utils/processJoinPlatformError.ts
  src/components/community/Platforms/components/LeaveModal/LeaveModal.tsx
  src/components/community/Platforms/components/LeaveModal/hooks/useLeaveModalMachine.ts
  src/components/community/Platforms/components/LeaveModal/utils/processLeavePlatformError.ts
  src/utils/processMetaMaskError.ts
Labels: agora-frontend, question, refactor

#47 Dynamic staking amounts
  src/components/allCommunities/CommunityCard.tsx
  src/components/community/Levels/components/InfoTags.tsx
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/Level/hooks/useLevelAccess.ts
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Levels/hooks/useNeededAmount.ts
  src/components/community/hooks/useTokenAllowance.ts
  src/components/community/hooks/useTokenAllowanceMachine.ts
  src/components/web3Connection/Account/Account.tsx
  src/hooks/useBalance.ts
  src/pages/[community].tsx
  src/pages/index.tsx
  src/temporaryData/types.ts
Labels: agora-frontend, invalid, question

#49 Estimate transaction time
  .env
  src/components/common/TransactionSubmitted.tsx
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Levels/components/StakingModal/hooks/useStakingMachine.ts
  src/components/community/Platforms/components/JoinModal/hooks/useJoinModalMachine.ts
  src/components/community/Platforms/components/PlatformButton/hooks/useIsMember.ts
  src/hooks/useEstimateTransactionTime.ts
  src/utils/msToReadableFormat.ts
Labels: agora-frontend, enhancement

#40 implement unstaking
  .eslintrc.json
  src/components/common/ActionCard.tsx
  src/components/community/Staked/Staked.tsx
  src/components/community/Staked/components/UnstakingModal/UnstakingModal.tsx
  src/components/community/Staked/components/UnstakingModal/hooks/useUnstakingMachine.ts
  src/components/community/Staked/components/UnstakingModal/utils/processUnstakingError.ts
  src/components/community/Staked/hooks/useStaked.ts
  src/components/community/Staked/utils/formatDate.ts
  src/components/community/hooks/useTokenAllowanceMachine.ts
Labels: agora-frontend, enhancement, question

#50 Responsiveness
  src/components/Layout.tsx
  src/components/allCommunities/CategorySection.tsx
  src/components/allCommunities/CommunityCard.tsx
  src/components/common/ActionCard.tsx
  src/components/common/Card.tsx
  src/components/common/Error.tsx
  src/components/common/Modal.tsx
  src/components/community/Levels/Levels.tsx
  src/components/community/Levels/components/AccessIndicator.tsx
  src/components/community/Levels/components/InfoTags.tsx
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/Level/components/AccessText/AccessText.tsx
  src/components/community/Levels/components/Level/components/AccessText/index.ts
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Platforms/Platforms.tsx
  src/components/community/Platforms/components/JoinModal/JoinModal.tsx
  src/components/community/Platforms/components/LeaveModal/LeaveModal.tsx
  src/components/community/Platforms/components/PlatformButton/PlatformButton.tsx
  src/components/community/Staked/Staked.tsx
  src/components/community/Staked/components/UnstakingModal/UnstakingModal.tsx
  src/components/web3Connection/AccountModal/AccountModal.tsx
  src/components/web3Connection/WalletSelectorModal/WalletSelectorModal.tsx
  src/pages/[community].tsx
  src/pages/index.tsx
  src/theme/colors.ts
  src/theme/components/modal.ts
Labels: agora-frontend, enhancement

#59 Dark mode
  src/components/Layout.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/components/ColorModeSwitch.tsx
  src/components/Layout/index.tsx
  src/components/_app/Chakra.tsx
  src/components/allCommunities/CommunityCard.tsx
  src/components/common/Card.tsx
  src/components/common/TransactionSubmitted.tsx
  src/components/community/Levels/components/AccessIndicator.tsx
  src/components/community/Levels/components/InfoTags.tsx
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/Level/components/AccessText.tsx
  src/components/community/Levels/components/Level/components/AccessText/index.ts
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Platforms/components/JoinModal/JoinModal.tsx
  src/components/community/Platforms/components/LeaveModal/LeaveModal.tsx
  src/components/community/Staked/components/UnstakingModal/UnstakingModal.tsx
  src/components/community/hooks/useColorPalette.ts
  src/components/web3Connection/Account/Account.tsx
  src/components/web3Connection/AccountModal/AccountModal.tsx
  src/components/web3Connection/WalletSelectorModal/WalletSelectorModal.tsx
  src/pages/[community].tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/theme/colors.ts
  src/theme/components/button.ts
  src/theme/components/index.ts
  src/theme/components/link.ts
  src/theme/components/tag.ts
  src/theme/components/text.ts
  src/theme/index.ts
Labels: agora-frontend, enhancement

#56 useBalance refactor
  src/components/community/Levels/components/Level/hooks/useLevelAccess.ts
  src/components/community/Levels/hooks/useNeededAmount.ts
  src/components/web3Connection/Account/Account.tsx
  src/hooks/useBalance.ts
Labels: agora-frontend, refactor

#57 Allowance component
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Staked/components/UnstakingModal/UnstakingModal.tsx
  src/components/community/common/TokenAllowance/TokenAllowance.tsx
  src/components/community/common/TokenAllowance/hooks/useTokenAllowance.ts
  src/components/community/common/TokenAllowance/hooks/useTokenAllowanceMachine.ts
  src/components/community/common/TokenAllowance/index.ts
Labels: agora-frontend, refactor

#65 Fixed shadow glitch on modals
  src/theme/components/modal.ts
Labels: invalid

#54 Categories on all communities page
  package-lock.json
  package.json
  src/components/allCommunities/CategorySection.tsx
  src/components/allCommunities/CommunityCard.tsx
  src/components/allCommunities/CommunityCard/CommunityCard.tsx
  src/components/allCommunities/CommunityCard/hooks/useIsMemberOfCommunity.ts
  src/components/allCommunities/CommunityCard/index.ts
  src/components/community/Context.tsx
  src/components/community/Levels/components/Level/hooks/useLevelAccess.ts
  src/pages/index.tsx
Labels: agora-frontend, enhancement

#66 Access/focus indicator refactor & pending state
  src/components/community/Levels/Levels.tsx
  src/components/community/Levels/components/AccessIndicator.tsx
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/Level/hooks/useLevelIndicatorState.ts
  src/components/community/Levels/components/Level/index.ts
Labels: agora-frontend, enhancement

#68 Improved useColorPalette hook
  src/components/community/hooks/useColorPalette.ts
Labels: invalid

#71 Commmunity data from backend
  public/temporaryCommunityLogos/agora.png
  public/temporaryCommunityLogos/agora1.png
  public/temporaryCommunityLogos/agora2.png
  public/temporaryCommunityLogos/agora3.png
  public/temporaryCommunityLogos/agora4.png
  src/components/allCommunities/CommunityCard/CommunityCard.tsx
  src/components/community/Context.tsx
  src/components/community/Levels/components/InfoTags.tsx
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/Level/hooks/useLevelAccess.ts
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Levels/components/StakingModal/hooks/useStakingMachine.ts
  src/components/community/Levels/hooks/useNeededAmount.ts
  src/components/community/Platforms/Platforms.tsx
  src/components/community/Platforms/components/PlatformButton/PlatformButton.tsx
  src/components/community/Platforms/components/PlatformButton/hooks/useIsMember.ts
  src/components/community/Platforms/platformsContent.ts
  src/components/community/Staked/components/UnstakingModal/hooks/useUnstakingMachine.ts
  src/components/community/Staked/hooks/useStaked.ts
  src/components/community/common/TokenAllowance/hooks/useTokenAllowance.ts
  src/pages/[community].tsx
  src/pages/index.tsx
  src/temporaryData/communities.ts
  src/temporaryData/types.ts
  src/theme/colors.ts
Labels: agora-frontend, question
