Repository AgoraSpaceDAO/agora-frontend, pull requests merged in 2021-09, with the labels that each got.

#111 SEO, accessibility, and performance improvements
  public/explorer_thumbnail.png
  public/robots.txt
  src/components/[community]/community/Levels/components/Level/Level.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/components/LogoWithMenu/LogoWithMenu.tsx
  src/components/index/CategorySection.tsx
  src/components/index/CommunityCard.tsx
  src/pages/[community]/community.tsx
  src/pages/[community]/index.tsx
  src/pages/index.tsx
  src/temporaryData/tokens.json
Labels: enhancement, agora-frontend

#131 Update community platforms
  src/components/admin/community/Levels/Levels.tsx
  src/components/admin/community/Platforms.tsx
  src/components/admin/hooks/useSubmitMachine.ts
  src/components/admin/hooks/useSubmitPlatformsData.ts
  src/pages/[community]/admin/community.tsx
Labels: enhancement, agora-frontend

#117 Store signed messages for session
  src/components/[community]/community/Platforms/components/JoinModal/JoinDiscordModal.tsx
  src/components/[community]/community/Platforms/components/JoinModal/JoinModal.tsx
  src/components/[community]/community/Platforms/components/JoinModal/hooks/useJoinModalMachine.ts
  src/components/[community]/community/Platforms/components/JoinModal/hooks/usePersonalSign.ts
  src/components/_app/PersonalSignStore.tsx
  src/components/admin/community/Levels/Levels.tsx
  src/components/admin/hooks/useSubmitMachine.ts
  src/pages/_app.tsx
Labels: enhancement, agora-frontend

#129 admin refactor & improvements
  src/components/[community]/common/Pagination.tsx
  src/components/[community]/common/Pagination/Pagination.tsx
  src/components/[community]/common/Pagination/components/PageButton.tsx
  src/components/[community]/common/Pagination/index.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/admin/common/ValidationError.tsx
  src/components/admin/community/Levels/Levels.tsx
  src/components/admin/community/Levels/components/AddLevel.tsx
  src/components/admin/community/Platforms.tsx
  src/components/admin/hooks/useSubmitMachine.ts
  src/components/admin/hooks/useSubmitPlatformsData.ts
  src/components/admin/index/Appearance.tsx
  src/components/admin/index/Details.tsx
  src/components/admin/index/Links.tsx
  src/components/admin/index/UsedToken/UsedToken.tsx
  src/components/admin/index/UsedToken/index.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkModal.tsx
  src/components/common/LinkButton.tsx
  src/pages/[community]/admin/community.tsx
  src/pages/[community]/admin/index.tsx
  src/pages/[community]/community.tsx
  src/pages/[community]/index.tsx
  src/pages/register/index.tsx
Labels: refactor

#132 Image uploading
  src/components/admin/community/Levels/Levels.tsx
  src/components/admin/community/Levels/components/AddLevel.tsx
  src/components/admin/hooks/useRedirectIfNotOwner.ts
  src/components/admin/hooks/useSubmitCommunityData.ts
  src/components/admin/hooks/useSubmitLevelsData.ts
  src/components/admin/hooks/useSubmitMachine.ts
  src/components/admin/hooks/useSubmitPlatformsData.ts
  src/components/admin/hooks/useUploadImages.ts
  src/components/admin/index/Details.tsx
  src/pages/[community]/admin/community.tsx
  src/pages/[community]/admin/index.tsx
  src/pages/register/index.tsx
Labels: enhancement, agora-frontend

#137 Trigger field validation on autofill from token address
  package-lock.json
  package.json
  src/components/admin/index/UsedToken/UsedToken.tsx
  src/components/admin/index/UsedToken/hooks/useTokenData.ts
Labels: bug, enhancement, agora-frontend

#139 Preview mode fix
  next.config.js
  src/components/admin/hooks/useSubmitCommunityData.ts
  src/components/admin/hooks/useSubmitLevelsData.ts
  src/components/admin/hooks/useSubmitPlatformsData.ts
  src/components/admin/hooks/useUploadImages.ts
  src/components/admin/index/Details.tsx
  src/components/admin/utils/setCookies.ts
  src/pages/[community]/admin/community.tsx
  src/pages/[community]/admin/info.tsx
  src/pages/api/preview.ts
  src/pages/register/index.tsx
Labels: enhancement, agora-frontend

#144 Revert NetworkChangeModal changes (made in I129)
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/admin/index/UsedToken/UsedToken.tsx
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
Labels: invalid, agora-frontend

#146 WalletConnect support
  next-env.d.ts
  package-lock.json
  package.json
  public/walletLogos/walletconnect.svg
  src/components/[community]/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/[community]/community/Levels/components/StakingModal/hooks/useStakingMachine.ts
  src/components/[community]/community/Platforms/components/JoinModal/JoinDiscordModal.tsx
  src/components/[community]/community/Platforms/components/JoinModal/hooks/useJoinModalMachine.ts
  src/components/[community]/community/Platforms/components/JoinModal/utils/processJoinPlatformError.ts
  src/components/[community]/community/Platforms/components/LeaveModal/hooks/useLeaveModalMachine.ts
  src/components/[community]/community/Staked/components/UnstakingModal/utils/processUnstakingError.ts
  src/components/[community]/community/Staked/hooks/useStaked.ts
  src/components/[community]/community/common/TokenAllowance/hooks/useTokenAllowanceMachine.ts
  src/components/[community]/hooks/useMemberCount.ts
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/utils/processConnectionError.ts
  src/components/_app/Web3ConnectionManager/hooks/useEagerConnect.ts
  src/components/_app/Web3ConnectionManager/hooks/useInactiveListener.ts
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkModal.tsx
  src/connectors.ts
  src/temporaryData/types.ts
  src/utils/processWalletError.ts
Labels: enhancement, agora-frontend

#145 Admin page - added a color picker
  src/components/admin/index/Appearance.tsx
Labels: enhancement, agora-frontend

#150 Sitemap
  public/robots.txt
  src/pages/[community]/admin/community.tsx
  src/pages/[community]/admin/info.tsx
  src/pages/sitemap.xml.tsx
Labels: enhancement, agora-frontend

#149 useContract deduping problem
  src/components/[community]/community/Staked/hooks/useStaked.ts
  src/components/[community]/community/common/TokenAllowance/hooks/useTokenAllowance.ts
  src/components/[community]/hooks/useMemberCount.ts
  src/hooks/useBalance.ts
  src/hooks/useContract.ts
  src/hooks/useEstimateTransactionTime.ts
Labels: enhancement, agora-frontend

#136 Pagination update & redesign
  src/components/[community]/common/Pagination/Pagination.tsx
  src/components/[community]/common/Pagination/components/PageButton.tsx
Labels: enhancement, agora-frontend
