Repository AgoraSpaceDAO/agora-frontend, pull requests merged in 2021-08, with the labels that each got.

#79 Request MetaMask network change if the user if on a wrong one
  src/components/allCommunities/CommunityCard.tsx
  src/components/community/Levels/components/Level/Level.tsx
  src/components/community/Levels/components/Level/hooks/useLevelAccess.ts
  src/components/community/Platforms/Platforms.tsx
  src/components/web3Connection/Account/Account.tsx
  src/components/web3Connection/Account/hooks/useRequestNetworkChange.ts
  src/connectors.ts
  src/temporaryData/communities.ts
Labels: agora-frontend, enhancement

#72 Improved typing
  src/components/_app/Chakra.tsx
  src/components/common/Card.tsx
  src/components/common/Link.tsx
  src/components/common/ModalButton.tsx
  src/components/common/TransactionSubmitted.tsx
  src/components/community/Levels/components/AccessIndicator.tsx
  src/components/community/Levels/components/InfoTags.tsx
  src/components/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/community/Levels/components/StakingModal/hooks/useStakingMachine.ts
  src/components/community/Platforms/components/JoinModal/hooks/useJoinModalMachine.ts
  src/components/community/Platforms/components/JoinModal/hooks/usePersonalSign.ts
  src/components/community/Platforms/components/JoinModal/utils/processJoinPlatformError.ts
  src/components/community/Platforms/components/LeaveModal/hooks/useLeaveModalMachine.ts
  src/components/community/Platforms/platformsContent.ts
  src/components/community/Staked/components/UnstakingModal/UnstakingModal.tsx
  src/components/community/Staked/components/UnstakingModal/hooks/useUnstakingMachine.ts
  src/components/community/common/TokenAllowance/hooks/useTokenAllowance.ts
  src/components/community/common/TokenAllowance/hooks/useTokenAllowanceMachine.ts
  src/components/web3Connection/Web3ConnectionManager/hooks/useInactiveListener.ts
  src/hooks/useBalance.ts
  src/hooks/useBlockNumber.ts
  src/hooks/useContract.ts
  src/hooks/useEstimateTransactionTime.ts
  src/hooks/useKeepSWRDataLiveAsBlocksArrive.ts
  src/temporaryData/types.ts
  src/utils/processMetaMaskError.ts
Labels: agora-frontend, refactor

#83 New tokens.json with holdersCount
  src/components/allCommunities/CommunityCard.tsx
  src/temporaryData/tokens.json
  src/temporaryData/tokens.ts
  src/temporaryData/types.ts
Labels: agora-frontend, enhancement

#86 Network change modal
  public/networkLogos/bsc.svg
  public/networkLogos/ethereum.svg
  public/networkLogos/polygon.svg
  src/components/community/Context.tsx
  src/components/web3Connection/Account/Account.tsx
  src/components/web3Connection/Account/components/Balance.tsx
  src/components/web3Connection/Account/components/NetworkModal/NetworkModal.tsx
  src/components/web3Connection/Account/components/NetworkModal/components/NetworkButton.tsx
  src/components/web3Connection/Account/components/NetworkModal/index.ts
  src/components/web3Connection/Account/hooks/useRequestNetworkChange.ts
  src/connectors.ts
  src/temporaryData/types.ts
Labels: agora-frontend, enhancement

#87 Discord auth
  .env
  .env.development
  .env.production
  src/components/community/Platforms/components/JoinDiscordModal/JoinDiscordModal.tsx
  src/components/community/Platforms/components/JoinDiscordModal/hooks/useJoinDiscordMachine.ts
  src/components/community/Platforms/components/JoinDiscordModal/index.ts
  src/components/community/Platforms/components/JoinDiscordModal/utils/processJoinPlatformError.ts
  src/components/community/Platforms/components/PlatformButton/PlatformButton.tsx
  src/components/community/Platforms/platformsContent.ts
  src/pages/dcauth.tsx
Labels: agora-frontend, enhancement

#81 Dynamic member count
  src/components/allCommunities/CommunityCard.tsx
  src/components/community/Context.tsx
  src/components/community/hooks/useMemberCount.ts
  src/temporaryData/communities.ts
  src/temporaryData/types.ts
Labels: agora-frontend, enhancement

#89 Small fixes, refactors
  src/components/Layout/components/LogoWithMenu.tsx
  src/components/allCommunities/CommunityCard.tsx
  src/components/common/Link.tsx
  src/components/community/Platforms/components/JoinDiscordModal/index.ts
  src/components/community/Platforms/components/JoinDiscordModal/utils/processJoinPlatformError.ts
  src/components/community/Platforms/components/JoinModal/JoinDiscordModal.tsx
  src/components/community/Platforms/components/JoinModal/JoinModal.tsx
  src/components/community/Platforms/components/JoinModal/hooks/useJoinDiscordMachine.ts
  src/components/community/Platforms/components/PlatformButton/PlatformButton.tsx
  src/components/community/Staked/utils/formatDate.ts
  src/components/web3Connection/Account/components/NetworkModal/NetworkModal.tsx
  src/components/web3Connection/Account/components/NetworkModal/components/NetworkButton/NetworkButton.tsx
  src/components/web3Connection/Account/components/NetworkModal/components/NetworkButton/index.ts
  src/components/web3Connection/Account/components/NetworkModal/utils/requestNetworkChange.ts
  src/components/web3Connection/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/web3Connection/WalletSelectorModal/utils/processConnectionError.ts
  src/components/web3Connection/Web3ConnectionManager/hooks/useEagerConnect.ts
Labels: agora-frontend, bug, refactor

#97 Multichain estimated transaction time
  .env
  README.md
  src/components/[community]/community/common/TransactionSubmitted.tsx
  src/hooks/useEstimateTransactionTime.ts
  src/pages/api/etherscan.ts
Labels: enhancement, agora-frontend

#101 RPC data fix
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButton/NetworkButton.tsx
  src/connectors.ts
Labels: bug, agora-frontend

#103 Join Discord flow improvements
  src/components/[community]/community/Levels/components/StakingModal/StakingModal.tsx
  src/components/[community]/community/Platforms/components/JoinModal/JoinDiscordModal.tsx
  src/components/[community]/community/Platforms/components/JoinModal/JoinModal.tsx
  src/components/[community]/community/Platforms/components/JoinModal/components/DCAuthButton.tsx
  src/components/[community]/community/Platforms/components/JoinModal/hooks/useDCAuthMachine.ts
  src/components/[community]/community/Platforms/components/JoinModal/hooks/useJoinModalMachine.ts
  src/components/[community]/community/Platforms/components/LeaveModal/LeaveModal.tsx
  src/components/[community]/community/Staked/components/UnstakingModal/UnstakingModal.tsx
  src/components/[community]/community/common/TokenAllowance/TokenAllowance.tsx
Labels: enhancement, agora-frontend

#98 SSG / SSR fixes & some performance improvements
  src/components/[community]/common/Context.tsx
  src/components/[community]/community/Levels/components/AccessIndicator/hooks/useWindowSize.ts
  src/components/[community]/hooks/useColorPalette.ts
  src/components/[community]/hooks/useMemberCount.ts
  src/components/index/CommunityCard.tsx
Labels: enhancement, agora-frontend, refactor

#112 Animating pending indicator only when it's visible
  src/components/[community]/community/Levels/components/AccessIndicator/AccessIndicator.tsx
Labels: invalid, agora-frontend

#109 Hash Discord user IDs
  src/pages/api/hash.ts
  src/pages/dcauth.tsx
Labels: enhancement, agora-frontend
